export const FETCH_THREADS_START = 'FETCH_THREADS_START';
export const FETCH_THREADS_SUCCESS = 'FETCH_THREADS_SUCCESS';
export const FETCH_THREADS_FAIL = 'FETCH_THREADS_FAIL';

export const SELECT_THREAD  = 'SELECT_THREAD';