export const FETCH_THREADS_START = 'FETCH_THREADS_START';
export const FETCH_THREADS_SUCCESS = 'FETCH_THREADS_SUCCESS';
export const FETCH_THREADS_FAIL = 'FETCH_THREADS_FAIL';

export const SELECT_THREAD_START = 'SELECT_THREAD_START';
export const SELECT_THREAD_SUCCESS = 'SELECT_THREAD_SUCCESS';
export const SELECT_THREAD_FAIL = 'SELECT_THREAD_FAIL';


export const CLEAR_THREADS = 'CLEAR_THREADS';

export const FETCH_MESSAGES_START = 'FETCH_MESSAGES_START';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const SELECT_THREAD  = 'SELECT_THREAD';

export const SEND_MESSAGE = 'SEND_MESSAGE';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT'; 
