export const FETCH_THREADS_START = 'FETCH_THREADS_START';
export const FETCH_THREADS_SUCCESS = 'FETCH_THREADS_SUCCESS';
export const FETCH_THREADS_FAIL = 'FETCH_THREADS_FAIL';

export const SELECT_THREAD_START = 'SELECT_THREAD_START';
export const SELECT_THREAD_SUCCESS = 'SELECT_THREAD_SUCCESS';
export const SELECT_THREAD_FAIL = 'SELECT_THREAD_FAIL';

export const FETCH_MESSAGES_START = 'FETCH_MESSAGES_START';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL';

export const SELECT_THREAD  = 'SELECT_THREAD';